### ISSUE TITLE
Failing mappings with the mapping.rml.ttl file

### ISSUE THREAD

**Issue by GenEars** [IBCNServices/Folio-Ontology#1]
Dear Folio team,
I wish I could use the `mapping.rml.ttl` file but I get the following issues:
```shell
docker run --rm -v $(pwd):/data rmlio/rmlmapper-java rmlmapper -m mapping.rml.ttl -o output.ttl -s turtle

# 15:50:50.479 [main] ERROR be.ugent.rml.cli.Main               .main(222) - Failed to make mapping file conformant to RML spec.
# # java.lang.Exception: Mapping requires at least one TriplesMap
#         at be.ugent.rml.conformer.MappingConformer.detect(MappingConformer.java:80)
#         at be.ugent.rml.conformer.MappingConformer.conform(MappingConformer.java:55)
#         at be.ugent.rml.cli.Main.main(Main.java:216)
#         at be.ugent.rml.cli.Main.main(Main.java:40)
# 15:50:50.572 [main] ERROR be.ugent.rml.cli.Main               .main(338) - No mapping was found for the function with IRI <http://example.com/idlab/functions/dyversify/generateIRI> in the function descriptions.
```

As there is no shared `electronics.csv` file available in the Folio repository, I created my own with fake data in order to run the tests:
```
Component,Function,Failure Mode,Failure Effect,Failure Cause,Control Method,Containment Action
C1,F1,FM1,FE1,FC1,CM1,CA1
```

Going a step further I wish I could reverse-engineer the `mapping.rml.ttl` file in order to solve issues but its content is not human friendly due to the RMLeditor factorization.

Hence could you please the give a piece of advice about this issue, such as:
* updating the `mapping.rml.ttl` file
* providing the RML mappings in a more human friendly format (e.g. a hand made mapping or a RMLeditor snapshot)
* adding the original `electronics.csv` file to the Folio repo 
* ...

Thanks.

**Comment by GenEars** [comment]
Dear @bsteenwi,
Your latest update #[9d7b438](https://github.com/IBCNServices/Folio-Ontology/commit/9d7b43830f67d35912175915350dfdb2b052ad43) (functions.ttl + DyversifyFunctions.java + mapping.yml + electronics.csv) allowed me to successfully start my testings.
Thanks !
